In [1]:
# joepareti54@gmail.com  April 25, 2022
# 
# do a linear regression exercise using pytorch nn nn.Module 
# customize a class which contains the forward method
# similar to the udacity exercise on MNIST at 
# finance-2022/AI/pytorch_youtube_april/tmp/*.pdf
# 
#

In [2]:
import numpy as np
import torch
from torch import nn, optim
torch.manual_seed(0)
x = torch.rand(5, dtype=torch.float32)
#
print(x)
y = 2*x
print(y)
# reshaping the arrays is needed to have one feature and as many samples as there are items in the array
Y = torch.reshape(y, (-1, 1))
X = torch.reshape(x, (-1, 1))
input_size  = Y.shape[1]
output_size = X.shape[1]
print(X)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([0.9925, 1.5364, 0.1770, 0.2641, 0.6148])
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074]])


In [3]:
print(input_size, output_size)

1 1


In [4]:
# in order to understand what input size and output size need to be for this case:
# https://stackoverflow.com/questions/54916135/what-is-the-class-definition-of-nn-linear-in-pytorch
# 
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred
        

In [5]:
alpha = 0.001
epochs = 10000


In [6]:
model = LinearRegression(input_size, output_size)
loss = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=alpha)
#

In [7]:
for i in range(epochs):
    optimizer.zero_grad()
    output = model(X)
    LOSS = loss(output, Y)
#    print(LOSS)
    LOSS.backward()
    optimizer.step()
    if i % 1000 == 0:
        print('epoch', i, 'loss', LOSS.item())

epoch 0 loss 0.598578691482544
epoch 1000 loss 0.07415773719549179
epoch 2000 loss 0.029219919815659523
epoch 3000 loss 0.006231018807739019
epoch 4000 loss 0.000497701286803931
epoch 5000 loss 7.459409061993938e-06
epoch 6000 loss 6.500679550214272e-09
epoch 7000 loss 3.099387500121731e-12
epoch 8000 loss 1.0896173286562005e-12
epoch 9000 loss 3.9102054927298013e-13


In [8]:
print('prediction', model(X))
print('label', Y)

prediction tensor([[0.9925],
        [1.5364],
        [0.1770],
        [0.2641],
        [0.6148]], grad_fn=<AddmmBackward>)
label tensor([[0.9925],
        [1.5364],
        [0.1770],
        [0.2641],
        [0.6148]])
